A = input("Digite A:")
B = input("Digite B:")
C = input("Digite C:")

print("A ^ B:",bool(A and B))
print("A ^ C:",bool(A and C))
print("B v C:",bool(B or C))
print("A ^ B ^ C:",bool(A and B and C))
print("~A v B",bool((not A) or B))
print("~A v ~C:",bool((not A) or (not C)))
print("(~A v B) ^ C:",bool(((not A) or B) and C))
print("~A ^ ~B ^ ~C:",bool((not A) and (not B) and (not C)))
print("~(A v B v C):")
print("A ^ False:")
print("A ^ ~A:")
print("A v ~A:")